### PR TITLE
ENH: Add larsoner, automerge, 3.7-3.10, use larsoner/openmeeg:conda-forge

### PR DESCRIPTION
**Pull request by larsoner**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- [x] Fix license name
- [x] Migrate to 3.7-3.10
- [x] Add @larsoner as a maintainer
- [x] Add bot automerge
- [x] Fix cmake macOS bug in openmeeg itself
- [x] Improve test to at least run some tiny code snippet
- [x] Fix linear algebra linking
- [x] Use ninja for improved speed on Windows
- [ ] ~~Fix LNK2001 `basic_osstream` error on Windows~~

### CODE REVIEW

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
FYI locally I added `.ci_support/migrations/python310.yaml` with:
<details>
<summary>.ci_support/migrations/python310.yaml</summary>

```
migrator_ts: 1634137107
__migrator:
    migration_number: 1
    operation: key_add
    primary_key: python
    ordering:
        python:
            - 3.6.* *_cpython
            - 3.7.* *_cpython
            - 3.8.* *_cpython
            - 3.9.* *_cpython
            - 3.10.* *_cpython  # new entry
            - 3.6.* *_73_pypy
            - 3.7.* *_73_pypy
    paused: false
    longterm: True
    pr_limit: 40
    max_solver_attempts: 10  # this will make the bot retry "not solvable" stuff 10 times
    exclude:
      # this shouldn't attempt to modify the python feedstocks
      - python
      - pypy3.6
      - pypy-meta
      - cross-python
      - python_abi
    exclude_pinned_pkgs: false

python:
  - 3.10.* *_cpython
# additional entries to add for zip_keys
numpy:
  - 1.21
python_impl:
  - cpython
```

</details>

which I borrowed from `mayavi`. Then I locally ran `conda-smithy rerender` and committed the changes. Not 100% sure it's correct, but CIs are at least running now.

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Review by agramfort — APPROVED** [review]

**Pull request merged**
